// <auto-generated />
namespace Ignite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImageInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061225378_Image Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
